import "vfile";

declare module "vfile" {
  interface DataMap {
    /**
     * Parsed frontmatter generated by vfile-matter.
     * This is whatever the YAML/TOML parser returns.
     */
    matter?: Record<string, unknown>;

    /**
     * Optional convenience alias we add in our plugin.
     */
    frontmatter?: Record<string, unknown>;
  }
}
